name: Build and Release

on:
  push:   # запускаем на любой пуш
    branches:
      - "**"   # любые ветки
    tags:
      - "v*"   # и на пуш тега (например v1.0.0)

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: windows
          - runner: macos
            arch: arm64
    runs-on: ${{ matrix.runner }}-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Calculate version
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
          fi
          echo "__version__ = '${VERSION}'" > version.py
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build binary with PyInstaller
        shell: bash
        env:
          ARCH: ${{ matrix.arch }}
        run: pyinstaller --onefile --console ${ARCH:+--target-architecture $ARCH} --name "pug-${VERSION}-${{ matrix.runner }}${ARCH:+-$ARCH}" pug.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pug-${{ matrix.runner }}
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'   # только если пуш тега
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/pug*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
