name: Build and Release

on:
  push:   # запускаем на любой пуш
    branches:
      - "**"   # любые ветки
    tags:
      - "v*"   # и на пуш тега (например v1.0.0)

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            ext: .exe
          - runner: macos-latest
            ext: ""
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile --console pug.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pug-${{ matrix.runner }}
          path: dist/pug${{ matrix.ext }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')   # только если пуш тега

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/pug.exe
            artifacts/**/pug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
